export { default as automation_webp } from './assets/images/cards/automation.webp';
export { default as blog_vector_webp } from './assets/images/cards/blog_vector.webp';
export { default as web_dev_webp } from './assets/images/cards/web_dev.webp';
export { default as design_responsivo_webp } from './assets/images/design_responsivo.webp';
export { default as og_image_html_webp } from './assets/images/og_image_html.webp';
export { default as pagespeed_lighthouse_webm } from './assets/images/pagespeed_lighthouse.webp';
export { default as website_portfolio_webm } from './assets/images/website_portfolio.webp';
export { default as codepen_svg } from './assets/svgs/codepen.svg';
export { default as github_svg } from './assets/svgs/github.svg';
export { default as hamburger_svg } from './assets/svgs/hamburger.svg';
export { default as heart_svg } from './assets/svgs/heart.svg';
export { default as linkedin_svg } from './assets/svgs/linkedin.svg';
export { default as twitter_svg } from './assets/svgs/twitter.svg';
export { default as whatsapp_svg } from './assets/svgs/whatsapp.svg';
export { default as fiverr_svg } from './assets/svgs/fiverr.svg';
export { default as app_99_svg } from './assets/svgs/99.svg';
export { default as upwork_svg } from './assets/svgs/upwork.svg';
// export { default as design_responsivo_webm } from './assets/videos/design_responsivo.webm';

export { default as arabesco_tiny_webp } from './assets/images/project_cards/arabesco_tiny.webp';
export { default as sys_vet_tiny_webp } from './assets/images/project_cards/sys_vet_tiny.webp';
export { default as sistemawebvet1_webp } from './assets/images/project_cards/sistemawebvet1.webp';
export { default as sistemawebvet2_webp } from './assets/images/project_cards/sistemawebvet2.webp';
export { default as sistemawebvet3_webp } from './assets/images/project_cards/sistemawebvet3.webp';
export { default as sistemawebvet4_webp } from './assets/images/project_cards/sistemawebvet4.webp';

export { default as my_menthor_tiny_webp } from './assets/images/project_cards/my_menthor_tiny.webp';
export { default as game_company_tiny_webp } from './assets/images/project_cards/game_company_tiny.webp';
export { default as legend_of_heroes_tiny_webp } from './assets/images/project_cards/legend_of_heroes_tiny.webp';
export { default as brazil_svg } from './assets/svgs/brazil.svg';
export { default as usa_svg } from './assets/svgs/usa.svg';
